version: '2.1'
orbs:
  ruby: circleci/ruby@2.0.0
jobs:
  build:
    docker:
      - image: 'cimg/ruby:3.2'
    steps:
      - checkout
      - run:
          command: 'bundle install --full-index'
          name: bundle install
  checking:
    docker:
      - image: 'cimg/ruby:3.2'
    steps:
      - checkout
      - run:
          command: 'gem install bundle && gem install rails'
          name: Install latest Bundle
      - run:
          command: 'bundle install --full-index'
          name: bundle install
      - ruby/rubocop-check:
          check-path: app
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: 'cimg/ruby:3.2'
      - environment:
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: circleci-demo-ruby
        image: 'circleci/postgres:9.5-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: circleci-demo-ruby
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - run:
          command: 'gem install bundle && gem install rails && bundle install'
          name: Install latest Bundle
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - run:
          command: 'bundle exec rspec'
          name: run rspec
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
