name: Deploy Rails App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: bundle install

    - name: Deploy to production
      run: |
        bundle exec db:migrate
        bundle exec assets:precompile
